import React from "react";

import { Container, Balls } from "./styles";

const Separator = ({ children }) => {
  return (
    <Container>
      {children}
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      {/*  */}
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
      <Balls />
    </Container>
  );
};

export default Separator;
